# cSpell:words goreleaser
name: Release new semantic version
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  goreleaser:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

  check_brew:
    name: Check Brew Tap
    needs: goreleaser
    runs-on: macos-latest
    steps:
      - name: Install with brew
        run: |
          brew install joshmedeski/sesh/sesh
      # TODO: assert the latest version was installed
